### ISSUE TITLE
Bug in mirrored matching

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts#261]
We hit this problem matching 2021-04-19
```
Build:2021-04-18: 100%|██████████████████████████████████████████████████████████| 765/765 [00:00<00:00, 18642.11it/s] 
Preprocess: 100%|█████████████████████████████████████████████████████████████████| 1000/1000 [00:11<00:00, 87.16it/s]
ms-match (1/0)100%|████████████████████████████████████████████████████████████████████████| 696/696 [00:56, 12.3it/s] 
ms-match (1/0)100%|████████████████████████████████████████████████████████████████████████| 357/357 [01:31, 3.89it/s] 
ms-match (1/0)100%|████████████████████████████████████████████████████████████████████████| 163/163 [02:02, 1.33it/s] 
ms-match (1/0)100%|██████████████████████████████████████████████████████████████████████| 4.00/4.00 [00:21, 5.46s/it] 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                 
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code                                                            
    exec(code, run_globals)                                
  File "/scratch/jk/work/github/sc2ts/sc2ts/__main__.py", line 5, in <module>                                          
    cli.cli()                                              
  File "/home/jk/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__                             
    return self.main(*args, **kwargs)
  File "/home/jk/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main                                 
    rv = self.invoke(ctx)                                  
  File "/home/jk/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke                               
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                            
  File "/home/jk/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke                               
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jk/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke                                
    return __callback(*args, **kwargs)
  File "/scratch/jk/work/github/sc2ts/sc2ts/cli.py", line 345, in extend                                               
    ts_out = inference.extend(
  File "/scratch/jk/work/github/sc2ts/sc2ts/inference.py", line 604, in extend                                         
    samples = match_samples(                               
  File "/scratch/jk/work/github/sc2ts/sc2ts/inference.py", line 479, in match_samples                                  
    match_tsinfer(                                         
  File "/scratch/jk/work/github/sc2ts/sc2ts/inference.py", line 1295, in match_tsinfer                                 
    manager = Matcher(                                     
  File "/home/jk/.local/lib/python3.9/site-packages/tsinfer/inference.py", line 1653, in __init__                      
    self.restore_tree_sequence_builder()
  File "/home/jk/.local/lib/python3.9/site-packages/tsinfer/inference.py", line 1672, in restore_tree_sequence_builder 
    raise ValueError("Invalid left coordinates")
ValueError: Invalid left coordinates
```
Something happend matching 4 recombinants in the backward direction. Hopefully can reproduce by running any match backwards on 2021-04-18.

**Comment by jeromekelleher** [comment]
Not sure if this is still a problem. Can reopen if it resurfaces.
